import { AbsoluteFill, Sequence, useVideoConfig } from "remotion";
import { Scene } from "./Scene";
// In a real app, data.json would be generated by the engine
import data from "./data.json";

export const MainComposition = () => {
  const { fps } = useVideoConfig();

  return (
    <AbsoluteFill>
      {data.scenes.map((scene: any, index: number) => {
        // Calculate start frame based on previous durations
        // For simplicity in this template, we assume the engine provides absolute start frames
        // or we calculate them here if we had a proper duration map.
        // Here we rely on the Sequence to handle timing if we knew the offsets.
        // But better: The Engine should write 'startFrame' into data.json.

        return (
          <Sequence
            key={scene.id}
            from={scene.startFrame}
            durationInFrames={scene.durationFrames}
          >
            <Scene
              type={scene.type}
              data={scene}
              imagePath={scene.image || "placeholder.png"}
            />
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};
